//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WsNAVManager.WebReferenceTHN_PROD {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="THN_WS_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/THN_WS")]
    public partial class THN_WS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UpdateVendorLedgerEntryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public THN_WS() {
            this.Url = global::WsNAVManager.Properties.Settings.Default.WsNAVManager_WebReferenceTHN_PROD_THN_WS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UpdateVendorLedgerEntryCompletedEventHandler UpdateVendorLedgerEntryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/THN_WS:UpdateVendorLedgerEntry", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/THN_WS", ResponseElementName="UpdateVendorLedgerEntry_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/THN_WS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public int UpdateVendorLedgerEntry(string _DocumentNo, int _Blocked) {
            object[] results = this.Invoke("UpdateVendorLedgerEntry", new object[] {
                        _DocumentNo,
                        _Blocked});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateVendorLedgerEntryAsync(string _DocumentNo, int _Blocked) {
            this.UpdateVendorLedgerEntryAsync(_DocumentNo, _Blocked, null);
        }
        
        /// <remarks/>
        public void UpdateVendorLedgerEntryAsync(string _DocumentNo, int _Blocked, object userState) {
            if ((this.UpdateVendorLedgerEntryOperationCompleted == null)) {
                this.UpdateVendorLedgerEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateVendorLedgerEntryOperationCompleted);
            }
            this.InvokeAsync("UpdateVendorLedgerEntry", new object[] {
                        _DocumentNo,
                        _Blocked}, this.UpdateVendorLedgerEntryOperationCompleted, userState);
        }
        
        private void OnUpdateVendorLedgerEntryOperationCompleted(object arg) {
            if ((this.UpdateVendorLedgerEntryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateVendorLedgerEntryCompleted(this, new UpdateVendorLedgerEntryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void UpdateVendorLedgerEntryCompletedEventHandler(object sender, UpdateVendorLedgerEntryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateVendorLedgerEntryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateVendorLedgerEntryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591