//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WsNAVManager.WebReferenceTWKSPA_PROD {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceReport_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport")]
    public partial class ServiceReport : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ChangeConfStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNewConfStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResAvailabilityOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangeServiceReportWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangeServiceReportWSToStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback CallPrintItemLabelsWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback PrintItemLabelsWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback CallPrintRcptLabelsWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback PrintRcptLabelsWSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceReport() {
            this.Url = global::WsNAVManager.Properties.Settings.Default.WsNAVManager_WebReferenceTWKSPA_PROD_ServiceReport;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ChangeConfStatusCompletedEventHandler ChangeConfStatusCompleted;
        
        /// <remarks/>
        public event GetNewConfStatusCompletedEventHandler GetNewConfStatusCompleted;
        
        /// <remarks/>
        public event ResAvailabilityCompletedEventHandler ResAvailabilityCompleted;
        
        /// <remarks/>
        public event ChangeServiceReportWSCompletedEventHandler ChangeServiceReportWSCompleted;
        
        /// <remarks/>
        public event ChangeServiceReportWSToStatusCompletedEventHandler ChangeServiceReportWSToStatusCompleted;
        
        /// <remarks/>
        public event CallPrintItemLabelsWSCompletedEventHandler CallPrintItemLabelsWSCompleted;
        
        /// <remarks/>
        public event PrintItemLabelsWSCompletedEventHandler PrintItemLabelsWSCompleted;
        
        /// <remarks/>
        public event CallPrintRcptLabelsWSCompletedEventHandler CallPrintRcptLabelsWSCompleted;
        
        /// <remarks/>
        public event PrintRcptLabelsWSCompletedEventHandler PrintRcptLabelsWSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ServiceReport:ChangeConfStatus", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", ResponseElementName="ChangeConfStatus_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ChangeConfStatus(int fromStatus, int toStatus, string reportHeaderNo, ref int errorWS) {
            object[] results = this.Invoke("ChangeConfStatus", new object[] {
                        fromStatus,
                        toStatus,
                        reportHeaderNo,
                        errorWS});
            errorWS = ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeConfStatusAsync(int fromStatus, int toStatus, string reportHeaderNo, int errorWS) {
            this.ChangeConfStatusAsync(fromStatus, toStatus, reportHeaderNo, errorWS, null);
        }
        
        /// <remarks/>
        public void ChangeConfStatusAsync(int fromStatus, int toStatus, string reportHeaderNo, int errorWS, object userState) {
            if ((this.ChangeConfStatusOperationCompleted == null)) {
                this.ChangeConfStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeConfStatusOperationCompleted);
            }
            this.InvokeAsync("ChangeConfStatus", new object[] {
                        fromStatus,
                        toStatus,
                        reportHeaderNo,
                        errorWS}, this.ChangeConfStatusOperationCompleted, userState);
        }
        
        private void OnChangeConfStatusOperationCompleted(object arg) {
            if ((this.ChangeConfStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeConfStatusCompleted(this, new ChangeConfStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ServiceReport:GetNewConfStatus", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", ResponseElementName="GetNewConfStatus_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetNewConfStatus(int fromStatus, string reportHeaderNo) {
            this.Invoke("GetNewConfStatus", new object[] {
                        fromStatus,
                        reportHeaderNo});
        }
        
        /// <remarks/>
        public void GetNewConfStatusAsync(int fromStatus, string reportHeaderNo) {
            this.GetNewConfStatusAsync(fromStatus, reportHeaderNo, null);
        }
        
        /// <remarks/>
        public void GetNewConfStatusAsync(int fromStatus, string reportHeaderNo, object userState) {
            if ((this.GetNewConfStatusOperationCompleted == null)) {
                this.GetNewConfStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewConfStatusOperationCompleted);
            }
            this.InvokeAsync("GetNewConfStatus", new object[] {
                        fromStatus,
                        reportHeaderNo}, this.GetNewConfStatusOperationCompleted, userState);
        }
        
        private void OnGetNewConfStatusOperationCompleted(object arg) {
            if ((this.GetNewConfStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewConfStatusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ServiceReport:ResAvailability", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", ResponseElementName="ResAvailability_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public decimal ResAvailability(string pCodRes, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime pDate) {
            object[] results = this.Invoke("ResAvailability", new object[] {
                        pCodRes,
                        pDate});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void ResAvailabilityAsync(string pCodRes, System.DateTime pDate) {
            this.ResAvailabilityAsync(pCodRes, pDate, null);
        }
        
        /// <remarks/>
        public void ResAvailabilityAsync(string pCodRes, System.DateTime pDate, object userState) {
            if ((this.ResAvailabilityOperationCompleted == null)) {
                this.ResAvailabilityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResAvailabilityOperationCompleted);
            }
            this.InvokeAsync("ResAvailability", new object[] {
                        pCodRes,
                        pDate}, this.ResAvailabilityOperationCompleted, userState);
        }
        
        private void OnResAvailabilityOperationCompleted(object arg) {
            if ((this.ResAvailabilityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResAvailabilityCompleted(this, new ResAvailabilityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ServiceReport:ChangeServiceReportWS", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", ResponseElementName="ChangeServiceReportWS_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public int ChangeServiceReportWS(int _FromStatus, int _ToStatus, string _ReportHeaderNo) {
            object[] results = this.Invoke("ChangeServiceReportWS", new object[] {
                        _FromStatus,
                        _ToStatus,
                        _ReportHeaderNo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeServiceReportWSAsync(int _FromStatus, int _ToStatus, string _ReportHeaderNo) {
            this.ChangeServiceReportWSAsync(_FromStatus, _ToStatus, _ReportHeaderNo, null);
        }
        
        /// <remarks/>
        public void ChangeServiceReportWSAsync(int _FromStatus, int _ToStatus, string _ReportHeaderNo, object userState) {
            if ((this.ChangeServiceReportWSOperationCompleted == null)) {
                this.ChangeServiceReportWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeServiceReportWSOperationCompleted);
            }
            this.InvokeAsync("ChangeServiceReportWS", new object[] {
                        _FromStatus,
                        _ToStatus,
                        _ReportHeaderNo}, this.ChangeServiceReportWSOperationCompleted, userState);
        }
        
        private void OnChangeServiceReportWSOperationCompleted(object arg) {
            if ((this.ChangeServiceReportWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeServiceReportWSCompleted(this, new ChangeServiceReportWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ServiceReport:ChangeServiceReportWSToStat" +
            "us", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", ResponseElementName="ChangeServiceReportWSToStatus_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public int ChangeServiceReportWSToStatus(int _ToStatus, string _ReportHeaderNo) {
            object[] results = this.Invoke("ChangeServiceReportWSToStatus", new object[] {
                        _ToStatus,
                        _ReportHeaderNo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeServiceReportWSToStatusAsync(int _ToStatus, string _ReportHeaderNo) {
            this.ChangeServiceReportWSToStatusAsync(_ToStatus, _ReportHeaderNo, null);
        }
        
        /// <remarks/>
        public void ChangeServiceReportWSToStatusAsync(int _ToStatus, string _ReportHeaderNo, object userState) {
            if ((this.ChangeServiceReportWSToStatusOperationCompleted == null)) {
                this.ChangeServiceReportWSToStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeServiceReportWSToStatusOperationCompleted);
            }
            this.InvokeAsync("ChangeServiceReportWSToStatus", new object[] {
                        _ToStatus,
                        _ReportHeaderNo}, this.ChangeServiceReportWSToStatusOperationCompleted, userState);
        }
        
        private void OnChangeServiceReportWSToStatusOperationCompleted(object arg) {
            if ((this.ChangeServiceReportWSToStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeServiceReportWSToStatusCompleted(this, new ChangeServiceReportWSToStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ServiceReport:CallPrintItemLabelsWS", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", ResponseElementName="CallPrintItemLabelsWS_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public int CallPrintItemLabelsWS(int pReportID, string pUserID, string pPrinterName, string pItemNo, int pDocumentType, string pDocumentTypeTxt, string pDocumentNo, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime pDate, string pVendorCode, string pCodDestination, string pCodJobNo, string pCodShelvingUnit, string pUrl, string pPassword) {
            object[] results = this.Invoke("CallPrintItemLabelsWS", new object[] {
                        pReportID,
                        pUserID,
                        pPrinterName,
                        pItemNo,
                        pDocumentType,
                        pDocumentTypeTxt,
                        pDocumentNo,
                        pDate,
                        pVendorCode,
                        pCodDestination,
                        pCodJobNo,
                        pCodShelvingUnit,
                        pUrl,
                        pPassword});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CallPrintItemLabelsWSAsync(int pReportID, string pUserID, string pPrinterName, string pItemNo, int pDocumentType, string pDocumentTypeTxt, string pDocumentNo, System.DateTime pDate, string pVendorCode, string pCodDestination, string pCodJobNo, string pCodShelvingUnit, string pUrl, string pPassword) {
            this.CallPrintItemLabelsWSAsync(pReportID, pUserID, pPrinterName, pItemNo, pDocumentType, pDocumentTypeTxt, pDocumentNo, pDate, pVendorCode, pCodDestination, pCodJobNo, pCodShelvingUnit, pUrl, pPassword, null);
        }
        
        /// <remarks/>
        public void CallPrintItemLabelsWSAsync(int pReportID, string pUserID, string pPrinterName, string pItemNo, int pDocumentType, string pDocumentTypeTxt, string pDocumentNo, System.DateTime pDate, string pVendorCode, string pCodDestination, string pCodJobNo, string pCodShelvingUnit, string pUrl, string pPassword, object userState) {
            if ((this.CallPrintItemLabelsWSOperationCompleted == null)) {
                this.CallPrintItemLabelsWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallPrintItemLabelsWSOperationCompleted);
            }
            this.InvokeAsync("CallPrintItemLabelsWS", new object[] {
                        pReportID,
                        pUserID,
                        pPrinterName,
                        pItemNo,
                        pDocumentType,
                        pDocumentTypeTxt,
                        pDocumentNo,
                        pDate,
                        pVendorCode,
                        pCodDestination,
                        pCodJobNo,
                        pCodShelvingUnit,
                        pUrl,
                        pPassword}, this.CallPrintItemLabelsWSOperationCompleted, userState);
        }
        
        private void OnCallPrintItemLabelsWSOperationCompleted(object arg) {
            if ((this.CallPrintItemLabelsWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallPrintItemLabelsWSCompleted(this, new CallPrintItemLabelsWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ServiceReport:PrintItemLabelsWS", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", ResponseElementName="PrintItemLabelsWS_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PrintItemLabelsWS(int _ReportID, string _UserID, string _PrinterName, string _ItemNo, int _DocumentType, string _DocumentNo, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime _Date, string _VendorCode, string _CodDestination, string _CodJobNo, string _CodShelvingUnit) {
            this.Invoke("PrintItemLabelsWS", new object[] {
                        _ReportID,
                        _UserID,
                        _PrinterName,
                        _ItemNo,
                        _DocumentType,
                        _DocumentNo,
                        _Date,
                        _VendorCode,
                        _CodDestination,
                        _CodJobNo,
                        _CodShelvingUnit});
        }
        
        /// <remarks/>
        public void PrintItemLabelsWSAsync(int _ReportID, string _UserID, string _PrinterName, string _ItemNo, int _DocumentType, string _DocumentNo, System.DateTime _Date, string _VendorCode, string _CodDestination, string _CodJobNo, string _CodShelvingUnit) {
            this.PrintItemLabelsWSAsync(_ReportID, _UserID, _PrinterName, _ItemNo, _DocumentType, _DocumentNo, _Date, _VendorCode, _CodDestination, _CodJobNo, _CodShelvingUnit, null);
        }
        
        /// <remarks/>
        public void PrintItemLabelsWSAsync(int _ReportID, string _UserID, string _PrinterName, string _ItemNo, int _DocumentType, string _DocumentNo, System.DateTime _Date, string _VendorCode, string _CodDestination, string _CodJobNo, string _CodShelvingUnit, object userState) {
            if ((this.PrintItemLabelsWSOperationCompleted == null)) {
                this.PrintItemLabelsWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrintItemLabelsWSOperationCompleted);
            }
            this.InvokeAsync("PrintItemLabelsWS", new object[] {
                        _ReportID,
                        _UserID,
                        _PrinterName,
                        _ItemNo,
                        _DocumentType,
                        _DocumentNo,
                        _Date,
                        _VendorCode,
                        _CodDestination,
                        _CodJobNo,
                        _CodShelvingUnit}, this.PrintItemLabelsWSOperationCompleted, userState);
        }
        
        private void OnPrintItemLabelsWSOperationCompleted(object arg) {
            if ((this.PrintItemLabelsWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrintItemLabelsWSCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ServiceReport:CallPrintRcptLabelsWS", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", ResponseElementName="CallPrintRcptLabelsWS_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public int CallPrintRcptLabelsWS(int pReportID, string pUserID, string pDocumentNo, string pUrl, string pPassword) {
            object[] results = this.Invoke("CallPrintRcptLabelsWS", new object[] {
                        pReportID,
                        pUserID,
                        pDocumentNo,
                        pUrl,
                        pPassword});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CallPrintRcptLabelsWSAsync(int pReportID, string pUserID, string pDocumentNo, string pUrl, string pPassword) {
            this.CallPrintRcptLabelsWSAsync(pReportID, pUserID, pDocumentNo, pUrl, pPassword, null);
        }
        
        /// <remarks/>
        public void CallPrintRcptLabelsWSAsync(int pReportID, string pUserID, string pDocumentNo, string pUrl, string pPassword, object userState) {
            if ((this.CallPrintRcptLabelsWSOperationCompleted == null)) {
                this.CallPrintRcptLabelsWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallPrintRcptLabelsWSOperationCompleted);
            }
            this.InvokeAsync("CallPrintRcptLabelsWS", new object[] {
                        pReportID,
                        pUserID,
                        pDocumentNo,
                        pUrl,
                        pPassword}, this.CallPrintRcptLabelsWSOperationCompleted, userState);
        }
        
        private void OnCallPrintRcptLabelsWSOperationCompleted(object arg) {
            if ((this.CallPrintRcptLabelsWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallPrintRcptLabelsWSCompleted(this, new CallPrintRcptLabelsWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ServiceReport:PrintRcptLabelsWS", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", ResponseElementName="PrintRcptLabelsWS_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PrintRcptLabelsWS(int _ReportID, string _UserID, string _DocumentNo) {
            this.Invoke("PrintRcptLabelsWS", new object[] {
                        _ReportID,
                        _UserID,
                        _DocumentNo});
        }
        
        /// <remarks/>
        public void PrintRcptLabelsWSAsync(int _ReportID, string _UserID, string _DocumentNo) {
            this.PrintRcptLabelsWSAsync(_ReportID, _UserID, _DocumentNo, null);
        }
        
        /// <remarks/>
        public void PrintRcptLabelsWSAsync(int _ReportID, string _UserID, string _DocumentNo, object userState) {
            if ((this.PrintRcptLabelsWSOperationCompleted == null)) {
                this.PrintRcptLabelsWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrintRcptLabelsWSOperationCompleted);
            }
            this.InvokeAsync("PrintRcptLabelsWS", new object[] {
                        _ReportID,
                        _UserID,
                        _DocumentNo}, this.PrintRcptLabelsWSOperationCompleted, userState);
        }
        
        private void OnPrintRcptLabelsWSOperationCompleted(object arg) {
            if ((this.PrintRcptLabelsWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrintRcptLabelsWSCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void ChangeConfStatusCompletedEventHandler(object sender, ChangeConfStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeConfStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeConfStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int errorWS {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void GetNewConfStatusCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void ResAvailabilityCompletedEventHandler(object sender, ResAvailabilityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResAvailabilityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResAvailabilityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void ChangeServiceReportWSCompletedEventHandler(object sender, ChangeServiceReportWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeServiceReportWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeServiceReportWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void ChangeServiceReportWSToStatusCompletedEventHandler(object sender, ChangeServiceReportWSToStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeServiceReportWSToStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeServiceReportWSToStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void CallPrintItemLabelsWSCompletedEventHandler(object sender, CallPrintItemLabelsWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallPrintItemLabelsWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallPrintItemLabelsWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void PrintItemLabelsWSCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void CallPrintRcptLabelsWSCompletedEventHandler(object sender, CallPrintRcptLabelsWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallPrintRcptLabelsWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallPrintRcptLabelsWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void PrintRcptLabelsWSCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591