//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsNAVManager.WebReferenceTWK_DEV {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", ConfigurationName="WebReferenceTWK_DEV.ServiceReport_Port")]
    public interface ServiceReport_Port {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ServiceReport:ChangeConfStatus", ReplyAction="*")]
        WsNAVManager.WebReferenceTWK_DEV.ChangeConfStatus_Result ChangeConfStatus(WsNAVManager.WebReferenceTWK_DEV.ChangeConfStatus request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ServiceReport:ChangeConfStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<WsNAVManager.WebReferenceTWK_DEV.ChangeConfStatus_Result> ChangeConfStatusAsync(WsNAVManager.WebReferenceTWK_DEV.ChangeConfStatus request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome wrapper (GetNewConfStatus_Result) del messaggio GetNewConfStatus_Result non corrisponde al valore predefinito (GetNewConfStatus)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ServiceReport:GetNewConfStatus", ReplyAction="*")]
        WsNAVManager.WebReferenceTWK_DEV.GetNewConfStatus_Result GetNewConfStatus(WsNAVManager.WebReferenceTWK_DEV.GetNewConfStatus request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ServiceReport:GetNewConfStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<WsNAVManager.WebReferenceTWK_DEV.GetNewConfStatus_Result> GetNewConfStatusAsync(WsNAVManager.WebReferenceTWK_DEV.GetNewConfStatus request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome wrapper (ResAvailability_Result) del messaggio ResAvailability_Result non corrisponde al valore predefinito (ResAvailability)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ServiceReport:ResAvailability", ReplyAction="*")]
        WsNAVManager.WebReferenceTWK_DEV.ResAvailability_Result ResAvailability(WsNAVManager.WebReferenceTWK_DEV.ResAvailability request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ServiceReport:ResAvailability", ReplyAction="*")]
        System.Threading.Tasks.Task<WsNAVManager.WebReferenceTWK_DEV.ResAvailability_Result> ResAvailabilityAsync(WsNAVManager.WebReferenceTWK_DEV.ResAvailability request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome wrapper (ChangeServiceReportWS_Result) del messaggio ChangeServiceReportWS_Result non corrisponde al valore predefinito (ChangeServiceReportWS)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ServiceReport:ChangeServiceReportWS", ReplyAction="*")]
        WsNAVManager.WebReferenceTWK_DEV.ChangeServiceReportWS_Result ChangeServiceReportWS(WsNAVManager.WebReferenceTWK_DEV.ChangeServiceReportWS request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ServiceReport:ChangeServiceReportWS", ReplyAction="*")]
        System.Threading.Tasks.Task<WsNAVManager.WebReferenceTWK_DEV.ChangeServiceReportWS_Result> ChangeServiceReportWSAsync(WsNAVManager.WebReferenceTWK_DEV.ChangeServiceReportWS request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeConfStatus {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeConfStatus", Namespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", Order=0)]
        public WsNAVManager.WebReferenceTWK_DEV.ChangeConfStatusBody Body;
        
        public ChangeConfStatus() {
        }
        
        public ChangeConfStatus(WsNAVManager.WebReferenceTWK_DEV.ChangeConfStatusBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport")]
    public partial class ChangeConfStatusBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int fromStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int toStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string reportHeaderNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int errorWS;
        
        public ChangeConfStatusBody() {
        }
        
        public ChangeConfStatusBody(int fromStatus, int toStatus, string reportHeaderNo, int errorWS) {
            this.fromStatus = fromStatus;
            this.toStatus = toStatus;
            this.reportHeaderNo = reportHeaderNo;
            this.errorWS = errorWS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeConfStatus_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeConfStatus_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", Order=0)]
        public WsNAVManager.WebReferenceTWK_DEV.ChangeConfStatus_ResultBody Body;
        
        public ChangeConfStatus_Result() {
        }
        
        public ChangeConfStatus_Result(WsNAVManager.WebReferenceTWK_DEV.ChangeConfStatus_ResultBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport")]
    public partial class ChangeConfStatus_ResultBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int errorWS;
        
        public ChangeConfStatus_ResultBody() {
        }
        
        public ChangeConfStatus_ResultBody(int errorWS) {
            this.errorWS = errorWS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNewConfStatus", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", IsWrapped=true)]
    public partial class GetNewConfStatus {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", Order=0)]
        public int fromStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", Order=1)]
        public string reportHeaderNo;
        
        public GetNewConfStatus() {
        }
        
        public GetNewConfStatus(int fromStatus, string reportHeaderNo) {
            this.fromStatus = fromStatus;
            this.reportHeaderNo = reportHeaderNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNewConfStatus_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", IsWrapped=true)]
    public partial class GetNewConfStatus_Result {
        
        public GetNewConfStatus_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResAvailability", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", IsWrapped=true)]
    public partial class ResAvailability {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", Order=0)]
        public string pCodRes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", Order=1)]
        public string pDate;
        
        public ResAvailability() {
        }
        
        public ResAvailability(string pCodRes, string pDate) {
            this.pCodRes = pCodRes;
            this.pDate = pDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResAvailability_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", IsWrapped=true)]
    public partial class ResAvailability_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", Order=0)]
        public decimal return_value;
        
        public ResAvailability_Result() {
        }
        
        public ResAvailability_Result(decimal return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeServiceReportWS", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", IsWrapped=true)]
    public partial class ChangeServiceReportWS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", Order=0)]
        public int _FromStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", Order=1)]
        public int _ToStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", Order=2)]
        public string _ReportHeaderNo;
        
        public ChangeServiceReportWS() {
        }
        
        public ChangeServiceReportWS(int _FromStatus, int _ToStatus, string _ReportHeaderNo) {
            this._FromStatus = _FromStatus;
            this._ToStatus = _ToStatus;
            this._ReportHeaderNo = _ReportHeaderNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeServiceReportWS_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", IsWrapped=true)]
    public partial class ChangeServiceReportWS_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ServiceReport", Order=0)]
        public int return_value;
        
        public ChangeServiceReportWS_Result() {
        }
        
        public ChangeServiceReportWS_Result(int return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceReport_PortChannel : WsNAVManager.WebReferenceTWK_DEV.ServiceReport_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceReport_PortClient : System.ServiceModel.ClientBase<WsNAVManager.WebReferenceTWK_DEV.ServiceReport_Port>, WsNAVManager.WebReferenceTWK_DEV.ServiceReport_Port {
        
        public ServiceReport_PortClient() {
        }
        
        public ServiceReport_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceReport_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceReport_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceReport_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsNAVManager.WebReferenceTWK_DEV.ChangeConfStatus_Result WsNAVManager.WebReferenceTWK_DEV.ServiceReport_Port.ChangeConfStatus(WsNAVManager.WebReferenceTWK_DEV.ChangeConfStatus request) {
            return base.Channel.ChangeConfStatus(request);
        }
        
        public void ChangeConfStatus(int fromStatus, int toStatus, string reportHeaderNo, ref int errorWS) {
            WsNAVManager.WebReferenceTWK_DEV.ChangeConfStatus inValue = new WsNAVManager.WebReferenceTWK_DEV.ChangeConfStatus();
            inValue.Body = new WsNAVManager.WebReferenceTWK_DEV.ChangeConfStatusBody();
            inValue.Body.fromStatus = fromStatus;
            inValue.Body.toStatus = toStatus;
            inValue.Body.reportHeaderNo = reportHeaderNo;
            inValue.Body.errorWS = errorWS;
            WsNAVManager.WebReferenceTWK_DEV.ChangeConfStatus_Result retVal = ((WsNAVManager.WebReferenceTWK_DEV.ServiceReport_Port)(this)).ChangeConfStatus(inValue);
            errorWS = retVal.Body.errorWS;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsNAVManager.WebReferenceTWK_DEV.ChangeConfStatus_Result> WsNAVManager.WebReferenceTWK_DEV.ServiceReport_Port.ChangeConfStatusAsync(WsNAVManager.WebReferenceTWK_DEV.ChangeConfStatus request) {
            return base.Channel.ChangeConfStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsNAVManager.WebReferenceTWK_DEV.ChangeConfStatus_Result> ChangeConfStatusAsync(int fromStatus, int toStatus, string reportHeaderNo, int errorWS) {
            WsNAVManager.WebReferenceTWK_DEV.ChangeConfStatus inValue = new WsNAVManager.WebReferenceTWK_DEV.ChangeConfStatus();
            inValue.Body = new WsNAVManager.WebReferenceTWK_DEV.ChangeConfStatusBody();
            inValue.Body.fromStatus = fromStatus;
            inValue.Body.toStatus = toStatus;
            inValue.Body.reportHeaderNo = reportHeaderNo;
            inValue.Body.errorWS = errorWS;
            return ((WsNAVManager.WebReferenceTWK_DEV.ServiceReport_Port)(this)).ChangeConfStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsNAVManager.WebReferenceTWK_DEV.GetNewConfStatus_Result WsNAVManager.WebReferenceTWK_DEV.ServiceReport_Port.GetNewConfStatus(WsNAVManager.WebReferenceTWK_DEV.GetNewConfStatus request) {
            return base.Channel.GetNewConfStatus(request);
        }
        
        public void GetNewConfStatus(int fromStatus, string reportHeaderNo) {
            WsNAVManager.WebReferenceTWK_DEV.GetNewConfStatus inValue = new WsNAVManager.WebReferenceTWK_DEV.GetNewConfStatus();
            inValue.fromStatus = fromStatus;
            inValue.reportHeaderNo = reportHeaderNo;
            WsNAVManager.WebReferenceTWK_DEV.GetNewConfStatus_Result retVal = ((WsNAVManager.WebReferenceTWK_DEV.ServiceReport_Port)(this)).GetNewConfStatus(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsNAVManager.WebReferenceTWK_DEV.GetNewConfStatus_Result> WsNAVManager.WebReferenceTWK_DEV.ServiceReport_Port.GetNewConfStatusAsync(WsNAVManager.WebReferenceTWK_DEV.GetNewConfStatus request) {
            return base.Channel.GetNewConfStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsNAVManager.WebReferenceTWK_DEV.GetNewConfStatus_Result> GetNewConfStatusAsync(int fromStatus, string reportHeaderNo) {
            WsNAVManager.WebReferenceTWK_DEV.GetNewConfStatus inValue = new WsNAVManager.WebReferenceTWK_DEV.GetNewConfStatus();
            inValue.fromStatus = fromStatus;
            inValue.reportHeaderNo = reportHeaderNo;
            return ((WsNAVManager.WebReferenceTWK_DEV.ServiceReport_Port)(this)).GetNewConfStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsNAVManager.WebReferenceTWK_DEV.ResAvailability_Result WsNAVManager.WebReferenceTWK_DEV.ServiceReport_Port.ResAvailability(WsNAVManager.WebReferenceTWK_DEV.ResAvailability request) {
            return base.Channel.ResAvailability(request);
        }
        
        public decimal ResAvailability(string pCodRes, string pDate) {
            WsNAVManager.WebReferenceTWK_DEV.ResAvailability inValue = new WsNAVManager.WebReferenceTWK_DEV.ResAvailability();
            inValue.pCodRes = pCodRes;
            inValue.pDate = pDate;
            WsNAVManager.WebReferenceTWK_DEV.ResAvailability_Result retVal = ((WsNAVManager.WebReferenceTWK_DEV.ServiceReport_Port)(this)).ResAvailability(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsNAVManager.WebReferenceTWK_DEV.ResAvailability_Result> WsNAVManager.WebReferenceTWK_DEV.ServiceReport_Port.ResAvailabilityAsync(WsNAVManager.WebReferenceTWK_DEV.ResAvailability request) {
            return base.Channel.ResAvailabilityAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsNAVManager.WebReferenceTWK_DEV.ResAvailability_Result> ResAvailabilityAsync(string pCodRes, string pDate) {
            WsNAVManager.WebReferenceTWK_DEV.ResAvailability inValue = new WsNAVManager.WebReferenceTWK_DEV.ResAvailability();
            inValue.pCodRes = pCodRes;
            inValue.pDate = pDate;
            return ((WsNAVManager.WebReferenceTWK_DEV.ServiceReport_Port)(this)).ResAvailabilityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsNAVManager.WebReferenceTWK_DEV.ChangeServiceReportWS_Result WsNAVManager.WebReferenceTWK_DEV.ServiceReport_Port.ChangeServiceReportWS(WsNAVManager.WebReferenceTWK_DEV.ChangeServiceReportWS request) {
            return base.Channel.ChangeServiceReportWS(request);
        }
        
        public int ChangeServiceReportWS(int _FromStatus, int _ToStatus, string _ReportHeaderNo) {
            WsNAVManager.WebReferenceTWK_DEV.ChangeServiceReportWS inValue = new WsNAVManager.WebReferenceTWK_DEV.ChangeServiceReportWS();
            inValue._FromStatus = _FromStatus;
            inValue._ToStatus = _ToStatus;
            inValue._ReportHeaderNo = _ReportHeaderNo;
            WsNAVManager.WebReferenceTWK_DEV.ChangeServiceReportWS_Result retVal = ((WsNAVManager.WebReferenceTWK_DEV.ServiceReport_Port)(this)).ChangeServiceReportWS(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsNAVManager.WebReferenceTWK_DEV.ChangeServiceReportWS_Result> WsNAVManager.WebReferenceTWK_DEV.ServiceReport_Port.ChangeServiceReportWSAsync(WsNAVManager.WebReferenceTWK_DEV.ChangeServiceReportWS request) {
            return base.Channel.ChangeServiceReportWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsNAVManager.WebReferenceTWK_DEV.ChangeServiceReportWS_Result> ChangeServiceReportWSAsync(int _FromStatus, int _ToStatus, string _ReportHeaderNo) {
            WsNAVManager.WebReferenceTWK_DEV.ChangeServiceReportWS inValue = new WsNAVManager.WebReferenceTWK_DEV.ChangeServiceReportWS();
            inValue._FromStatus = _FromStatus;
            inValue._ToStatus = _ToStatus;
            inValue._ReportHeaderNo = _ReportHeaderNo;
            return ((WsNAVManager.WebReferenceTWK_DEV.ServiceReport_Port)(this)).ChangeServiceReportWSAsync(inValue);
        }
    }
}
