//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsNAVManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.141:7057/TWINPACK_DEV/WS/TWINPACK SPA/Codeunit/ServiceReport")]
        public string WsNAVManager_WebReferenceTHN_DEV_THN_WS {
            get {
                return ((string)(this["WsNAVManager_WebReferenceTHN_DEV_THN_WS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.141:7047/TWINPACK/WS/TWINPACK SPA/Codeunit/ServiceReport")]
        public string WsNAVManager_WebReferenceTHN_PROD_THN_WS {
            get {
                return ((string)(this["WsNAVManager_WebReferenceTHN_PROD_THN_WS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.141:7047/TWINPACK/WS/TWINPACK%20SPA/Codeunit/ServiceReport")]
        public string WsNAVManager_WebReferenceTWKSPA_PROD_ServiceReport {
            get {
                return ((string)(this["WsNAVManager_WebReferenceTWKSPA_PROD_ServiceReport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.141:7057/TWINPACK_DEV/WS/TWINPACK%20SPA/Codeunit/ServiceReport")]
        public string WsNAVManager_WebReferenceTWKSPA_DEV_ServiceReport {
            get {
                return ((string)(this["WsNAVManager_WebReferenceTWKSPA_DEV_ServiceReport"]));
            }
        }
    }
}
